<?php

$servername = "database";

// Database
$db_username = $_ENV["MYSQL_USER"];
$db_password = $_ENV["MYSQL_PASSWORD"];
$db_database = "maranzano";

// PHP Mailer
$email_host = $_ENV["EMAIL_HOST"];
$email_user = $_ENV["EMAIL_USER"];
$email_pass = $_ENV["EMAIL_PASSWORD"];

$domain_name = $_ENV["DOMAIN_NAME"];
$local_ip    = $_ENV["LOCAL_IP"];

?>